<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../third_party/CedarDotNet/src/CedarDotNet/CedarDotNet.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Stateless" Version="5.20.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
  </ItemGroup>
</Project>
